services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: WebApp20252709/Dockerfile
    container_name: webapp-api
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    volumes:
      - ./https:/https:ro


volumes:
  postgres_data:
